cd build/
make distclean
cmake .. -DCUT_OFF=6 -DCOM_FG_PSI=ON -DLARGE_INPUT=ON -DCUNFFT_DOUBLE_PRECISION=ON -DMILLI_SEC=OFF -DMEASURED_TIMES=OFF -DPRINT_CONFIG=OFF -DDEBUG=OFF -DTHREAD_DIM_X=256 -DTHREAD_DIM_Y=256 -LAH 
make #> makeLog.txt 2>&1 
make install 

